default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: shine_development

test:
  <<: *default
  database: shine_test

production:
  <<: *default
  database: shine_production
  username:
  password:
