# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb9149aefdde4c2dfe314d4f03f3953a0d6225b3a76786a49de591961618c974dc79a650b9c2e9e69a9750ae5eba42f499bc8eac394e7baf33e2e4c082a6909a

test:
  secret_key_base: 1eb9990da5240b38a73e883ec7fc9c51b6f8ea4f0075b89ca35dc8b1c703b887d81eebfd0b224f9d52e9b282c52ed173b2cb342a677201aa0bafdd76f34711e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
